### ISSUE TITLE
My neovim will not switch automatically

### ISSUE THREAD

**Issue by j2501987804** [brglng/vim-im-select#10]
The plugin status is normal and I have executed "ImSelectEnable", but pressing the back key for Chinese input does not switch back to English
os：ubunut22.04
editor：neovim8.1
ibus
GTK_IM_MODULE=ibus

**Comment by zhaosheng-pan** [comment]
Pressing the back key won't do the switch. You need to press Esc and switch to normal mode, and the IM will be switched at the same time.
