### ISSUE TITLE
fcitx5 命令检测有问题

### ISSUE THREAD

**Issue by Winson-Huang** [brglng/vim-im-select#13]
我在 Debian 12 中使用 fcitx，发现新版本的 fcitx5 对环境变量的设置已经变成 `fcitx` 了，所以最好不要用环境变量判断 fcitx/fcitx5，而应该使用其他方式。

![图片](https://github.com/brglng/vim-im-select/assets/47921347/f15e9f66-40af-4ba4-9761-9dedf6b0c503)

**Comment by Winson-Huang** [comment]
否则脚本中设置的切换输入法和检测输入法的命令根本不起作用。

**Comment by brglng** [comment]
Fixed in 27666b8
