### ISSUE TITLE
The plugin won't switch to Chinese input method after losting and regaining focus 

### ISSUE THREAD

**Issue by voldikss** [brglng/vim-im-select#3]
- 在 insert 模式下是中文输入法，

- 回到 normal 模式，

- 然后切换到其他应用再切换回来，

- 再次回到 insert 模式，却变成了英文输入法

```
NVIM v0.5.0-fa9b057

fcitx version: 4.2.9.7(fcitx-lilydjwg-git)

Arch Linux
```

**Comment by brglng** [comment]
Reproduced.

**Comment by brglng** [comment]
@voldikss Please try the latest commit and see if the bug is fixed.

**Comment by voldikss** [comment]
The issue still exists :cry:

**Comment by brglng** [comment]
Reproduced under Arch Linux + KDE + Fcitx

**Comment by brglng** [comment]
请问你是在 Konsole 下使用 nvim 吗？似乎默认情况下从其他程序切换到 Konsole 时，就会关闭 Fcitx。不确定这是 Konsole 还是 Fcitx 的功能。

**Comment by voldikss** [comment]
这样啊，我用的是 terminator

**Comment by voldikss** [comment]
那加一个 FocusGain，当窗口焦点切换回来时 check 一下，这样能不能解决呢

**Comment by voldikss** [comment]
OK我明天试试，已经快睡了

Zhaosheng Pan <notifications@github.com> 于 2020年5月22日周五 下午11:59写道：

**Comment by voldikss** [comment]
去掉之后没问题了。这两行是必须的吗？

**Comment by brglng** [comment]
如果系统已经会在不同应用间自动切换，这两行就会引起问题。我加个选项吧。

**Comment by brglng** [comment]
@voldikss 试一下最新版本？我加了一个选项 `g:im_select_enable_focus_evetns`，默认是 0

**Comment by voldikss** [comment]
完美解决！感谢！

**Comment by brglng** [comment]
@voldikss 为保持向后兼容，我还是把默认值设为 1 了，你需要自己设为 0。

**Comment by voldikss** [comment]
没问题的，我手动设置成了0
