### ISSUE TITLE
Need a guide on Windows (10)

### ISSUE THREAD

**Issue by bon-ami** [brglng/vim-im-select#6]
Though some say PowerShell has commands to support this, I doubt it can be used by this, so I did not look into them.
A guide on what the IME switching command is and how to configure this at all, would be so helpful.

**Comment by brglng** [comment]
Maybe I also need some help on this topic.

**Comment by yzlnew** [comment]
Check my post.
https://yzlnew.com/2019/01/vim-imselect/

**Comment by brglng** [comment]
Thank you @yzlnew . I have updated the default IM key and README.md according to your post.
