### ISSUE TITLE
When use Ctrl-c  to exit vim insert mode, will not trigger InsertLeave

### ISSUE THREAD

**Issue by fffx** [brglng/vim-im-select#9]
Workaround is ：
```
ino <C-C> <Esc>
```

find from: https://stackoverflow.com/questions/10757020/vim-insertleave-event-doesnt-occur-when-using-ctrl-c-instead-of-esc

**Comment by brglng** [comment]
I don't think I am able to fix this issue, as this is a limitation of Vim.

**Comment by fffx** [comment]
It's fine, post it there maybe useful for
 someone else. Thanks.
